### ISSUE TITLE
why p.stepSimulation() function may cause random action？

### ISSUE THREAD

**Issue by Hobbit-wgh** [utiasDSL/gym-pybullet-drones#154]
I try to rest my ur5 robot in two ways，but when meet  p.stepSimulation(), the robot will cause a random action.

first way:

`    def reset(self):`  
     `      self.mointor_force_torque = np.zeros((2, 240))`  
     `      for i in range(6):`  
      `         p.resetJointState(bodyUniqueId=self.ur5_id, jointIndex=i + 1, targetValue=self.init_joint_val[i])`  
     `      p.enableJointForceTorqueSensor(self.ur5_id, 7)`  
    `       p.stepSimulation()`

second way:

`    def reset(self):`  
    `       self.mointor_force_torque = np.zeros((2, 240))`  
    `      for i in range(6):`  
    `     p.setJointMotorControlArray(self.ur5_id, [1, 2, 3, 4, 5, 6],`  
                `                    controlMode=p.POSITION_CONTROL,`  
               `                        targetPositions=list(self.init_joint_val),`  
               `                        forces=np.array([87.0, 87.0, 87.0, 87.0, 60, 60]))`  
    `       p.enableJointForceTorqueSensor(self.ur5_id, 7)`  
      `     p.stepSimulation(1)`

**Comment by JacopoPan** [comment]
Hi again @Hobbit-wgh :D

there aren't UR5 robots in this repo, so I think you spend the issue in the wrong place.
