### ISSUE TITLE
Fly_thrugate reward function issue

### ISSUE THREAD

**Issue by abdul-mannan-khan** [utiasDSL/gym-pybullet-drones#160]
Hello @JacopoPan,

Thank you for sharing this repository. I am sorry to take little time but could you please let me know if singleagent.py is working on your computer for Flythrugate. In my case, it is not working. The reward function here 

https://github.com/utiasDSL/gym-pybullet-drones/blob/183c84a56c3f8a941fd7ec6c3e4308532b65b05e/gym_pybullet_drones/envs/single_agent_rl/FlyThruGateAviary.py#L106

is giving me negative reward and it keeps decreasing as shown in the Figure below. 

![Screenshot from 2023-07-10 12-31-26](https://github.com/utiasDSL/gym-pybullet-drones/assets/22067958/b16be72c-1b7f-470c-80ea-3dae7e9f31d4)

Could you please shed some light?

Thank you.

**Comment by JacopoPan** [comment]
Hi again :D,

please see #158 on the branch I recommend working on at this point in time (many of the dependencies of the `master` branch are unfortunately now deprecated or drifted from the originally used ones)
