### ISSUE TITLE
No TakeOffAviary.py in gym-pybullet-drones/gym_pybullet_drones/envs /single_agent_rl/

### ISSUE THREAD

**Issue by RibhavOjha** [utiasDSL/gym-pybullet-drones#168]
Hi
TakeOffAviary.py is not present in the path mentioned in the subject. 
Is it intentional? Because takeOffAviary is being used in experiments/learning/singleagent.py, and therefore giving import errors.

**Comment by JacopoPan** [comment]
Hi @RibhavOjha 

as we are discussing in #169 , you should checkout either the `master` or `paper` branch to look at the code from the IROS 2021 paper (this is mentioned at the top of the README in `main`).
