### ISSUE TITLE
ModuleNotFoundError: No module named 'gym_pybullet_drones'

### ISSUE THREAD

**Issue by ybl998877** [utiasDSL/gym-pybullet-drones#179]
when I run 'pid.py' ,report 'ModuleNotFoundError: No module named 'gym_pybullet_drones''.The model name and path are right,i dont konw why this error occurs.

**Comment by abdul-mannan-khan** [comment]
You need to 

`cd gym-pybullet-drones/`

```
conda create -n drones python=3.10
conda activate drones

pip3 install --upgrade pip
pip3 install -e . # if needed, `sudo apt install build-essential` to install `gcc` and build `pybullet`
```
If you will not run

`pip3 install -e . # if needed, `sudo apt install build-essential` to install `gcc` and build `pybullet``
from inside the directory 

`cd gym-pybullet-drones/`
 you will get the above mentioned error

**Comment by ybl998877** [comment]
Thanks very much! I run it successfully.

**Comment by JacopoPan** [comment]
Thanks @abdul-mannan-khan for answering before I could :D
