### ISSUE TITLE
Google colab support

### ISSUE THREAD

**Issue by aveen-d** [utiasDSL/gym-pybullet-drones#18]
Will this repo work on Google colab, as colab supports both gym and pybullet? I actually don't have any GPU available for RL training. Any work around with that?

**Comment by JacopoPan** [comment]
Hi @aveen-d,

this repo essentially contains subclasses of `Gym` as a python package, so I imagine [it would work with Colaboratory like any other custom package cloned from GitHub](https://stackoverflow.com/questions/53793731/using-custom-packages-on-google-colaboratory). But you raise a good point and I'll make a note to self to add Notebook examples.

Still, you are not strictly required to have GPU to run, edit, debug the code in this repo.
