### ISSUE TITLE
self.TIMESTEP not defined in BaseAviary Class

### ISSUE THREAD

**Issue by praneelacharya** [utiasDSL/gym-pybullet-drones#188]
When using custom physics which class _dynamics() from BaseAviary.py, it gives an error as the self.TIMESTEP is not defined in the BaseAviary.py. Thank you for sharing your work!

#### Update state ##########################################
        vel = vel + self.PYB_TIMESTEP * no_pybullet_dyn_accs
        rpy_rates = rpy_rates + self.PYB_TIMESTEP * rpy_rates_deriv
        pos = pos + self.PYB_TIMESTEP * vel
        quat = self._integrateQ(quat, rpy_rates, self.TIMESTEP)   #<------ THIS LINE
#### Set PyBullet's state ##################################

**Comment by JacopoPan** [comment]
Thanks for pointing this out, I believe it should be `self.PYB_TIMESTEP`.
You can open a PR if you want to contribute a bug fix, otherwise I will look at this in the upcoming days.
