### ISSUE TITLE
A Drag function mistake

### ISSUE THREAD

**Issue by ana-lys** [utiasDSL/gym-pybullet-drones#189]
If you are converting linear velocity from global coordinates to base coordinates, then the rotation should be inverse.
I suggest changing it to
```
        drag = np.dot(base_rot.T, drag_factors*np.array(self.vel[nth_drone, :]))
```
instead of
```
        drag = np.dot(base_rot, drag_factors*np.array(self.vel[nth_drone, :]))
```
The effect is neglectable when the rotation is small ( yaw = 0 ) so it makes this harder to notice.

**Comment by JacopoPan** [comment]
Hi @ana-lys: could you please open a PR with the recommended changes? Small contributions and bug fixes are always welcome and should be attributed properly
