### ISSUE TITLE
Some camera associated issues

### ISSUE THREAD

**Issue by ereshkigal224** [utiasDSL/gym-pybullet-drones#197]
Hello!When i was trying to set --record_video to value true and python informs me there is no such file or dictionary. I was wondering if i got something wrong.
![屏幕截图 2024-03-21 173205](https://github.com/utiasDSL/gym-pybullet-drones/assets/138562578/79bd8450-2e52-44f4-a3a5-4cd0342739b3)

**Comment by JacopoPan** [comment]
@ereshkigal224 

thank for noting this, it should work now!
