### ISSUE TITLE
Question about _computeReward in Multi Agent environment

### ISSUE THREAD

**Issue by mfarrelm** [utiasDSL/gym-pybullet-drones#20]
First of all, thank you for your work on this simulator.  I have a question, why is it using index 0 on getDroneStateVector instead of i. Is it a typo or maybe there is another meaning behind it?

~~~
  rewards = {}
  states = np.array([self._getDroneStateVector(0) for i in range(self.NUM_DRONES)])
  rewards[0] = -1 * np.linalg.norm(np.array([1, 1, 1]) - states[0, 0:3])**2
  for i in range(1, self.NUM_DRONES):
      rewards[i] = -1 * np.linalg.norm(states[i-1, 0:3] - states[i, 0:3])**2
  return rewards
~~~
This is from LeaderFollowerAviary.py.

**Comment by JacopoPan** [comment]
Thanks! It absolutely looks like a typo and had trickled to a couple of other places too. Should be fixed in the latest push.
