### ISSUE TITLE
has anyone successfully trained multi agent problem : flockaviary?

### ISSUE THREAD

**Issue by MuhammadFadhilArkan** [utiasDSL/gym-pybullet-drones#22]
First of all, thankyou for your work on this simulator.

after training flockaviary environment using multiagent.py for 200 iteration
![3](https://user-images.githubusercontent.com/68679339/107908329-5bb8b880-6f88-11eb-8aca-3c9a1e6ecffc.PNG)

then testing it using test_multiagent.py, the result is not as expected 
![2](https://user-images.githubusercontent.com/68679339/107908421-9589bf00-6f88-11eb-86b4-d4790df5055b.PNG)

as you can see, z position is above 100 even though from _computereward function we can see that the goal is to make multiple drones hover at z position =1 
![4](https://user-images.githubusercontent.com/68679339/107908681-38dad400-6f89-11eb-9b02-b4c12e14e48a.PNG)

after looking at progress.csv, the reward is already steady (around -29) , which i assume that increasing the number of iteration will not affect the performance.

is this a problem with environment (flockaviary.py) or the algorithm (multiagent.py) or something else?

**Comment by JacopoPan** [comment]
> is this a problem with environment (flockaviary.py) or the algorithm (multiagent.py) 

(there's something to say about action/observation types and the policy architectures but) the short answer is *both*: the reward function in `flockaviary.py` is the one you mention, not one necessarily intended for flocking, and `multiagent.py` is still the least mature piece of code in this repo (e.g., it needs work to extend to more than 2 drones)

you can use `test_multiagent.py` to have a look at what the trained policies are (and maybe infer where it is going wrong)

**Comment by JacopoPan** [comment]
I realized that `test_multiagent.py` was not working properly because the input to `compute_single_action()` was not in the correct order. The default execution of script `multiagent.py` (a 1D leader-follower example) can now be trained and tested in ~10'
![Figure_1](https://user-images.githubusercontent.com/19269261/108803808-982c7b80-7569-11eb-83ea-7c6b48a054fc.png)
