### ISSUE TITLE
 No module named 'gym_pybullet_drones'

### ISSUE THREAD

**Issue by DKKHerath** [utiasDSL/gym-pybullet-drones#230]
(drones) C:\WORKSPACE\Research\gym-pybullet-drones\gym_pybullet_drones\examples>python learn.py
Traceback (most recent call last):
  File "C:\WORKSPACE\Research\gym-pybullet-drones\gym_pybullet_drones\examples\learn.py", line 32, in <module>
    from gym_pybullet_drones.utils.Logger import Logger
ModuleNotFoundError: No module named 'gym_pybullet_drones'

**Comment by JacopoPan** [comment]
yes, please follow the instruction in the README @DKKHerath, the package is installed into a Conda environment via pip.
