### ISSUE TITLE
M2 Mac Failed to build pybullet

### ISSUE THREAD

**Issue by ishaanamahajan** [utiasDSL/gym-pybullet-drones#234]
I am trying to set up` gym-pybullet-drones` on my M2 Mac but it keeps failing with the following output - 

```
Successfully built gym-pybullet-drones
Failed to build pybullet
```

I have tried python <=3.10, and pybullet <=3.2.6, but none of the versions seem to be working. All of them throw out the same error. I would appreciate any help, thank you!

**Comment by ishaanamahajan** [comment]
UPDATE: using clang instead of gcc seems to have fixed it!

**Comment by zhankins** [comment]
How do you specify using clang instead of gcc? I'm having the same issue on an M4 Mac.
