### ISSUE TITLE
Get Drone States Across Multiple Environments

### ISSUE THREAD

**Issue by HovhannesTumanyan** [utiasDSL/gym-pybullet-drones#239]
In the "Learning to Fly—a Gym Environment with PyBullet Physics for
Reinforcement Learning of Multi-agent Quadcopter Control" article, parallelism and handling multiple environments were discussed. I'm looking to retrieve drone states across various environments (e.g., development, testing, production). I couldn't find relevant examples or functionality in the current codebase. Could you help by providing an example or pointing me in the right direction?

**Comment by JacopoPan** [comment]
Hello,

In the original paper there were performance considerations based on running multiple simulations with multiple drones/objects in multiple processes: https://github.com/utiasDSL/gym-pybullet-drones/blob/paper/experiments/performance/parallelism.sh (however these are not part of the current default codebase on `main`)
