### ISSUE TITLE
Question: Is there a way to control the drones by 1D thrust and 3D torques on the center of mass?

### ISSUE THREAD

**Issue by thaipduong** [utiasDSL/gym-pybullet-drones#24]
The control seems to be rpm of each rotors in fly.py. Is there a way to control the drones by 1D thrust and 3D torques on the center of mass?
Thank you. Appreciate your help.

**Comment by JacopoPan** [comment]
Hi @thaipduong,

I wrote this alternative aviary, internally using non-negative least squares to compute RPMs from input thrust and torques:
https://github.com/utiasDSL/gym-pybullet-drones/blob/962631269fcfe5ac2032a394248ec18aa6b72bf2/gym_pybullet_drones/envs/DynAviary.py#L7
https://github.com/utiasDSL/gym-pybullet-drones/blob/962631269fcfe5ac2032a394248ec18aa6b72bf2/gym_pybullet_drones/utils/utils.py#L58
I never used it extensively, though. Could you try it and see if it does the job you are looking for?

**Comment by thaipduong** [comment]
Thank you, @JacopoPan. I'll give it a try :).
