### ISSUE TITLE
Implementing a Custom Controller on Gym-Pybullet Drones

### ISSUE THREAD

**Issue by lakshmikanth-nageswar** [utiasDSL/gym-pybullet-drones#243]
Hi, could anyone please clear these queries of mine:

- How to modify the training tasks say for hover, single set-point (regularisation) and tracking problem through this framework? and for visualisation of trained policy in pybullet as well. (how to modify the BaseAviary or VelocityAviary for tracking and other scripts required to be modified?)

- How to implement our own controller (say linear or non-linear or learning based) in this environment

Thanks in Advance.

**Comment by JacopoPan** [comment]
I'm not sure I understood your first questions (most of those things are already implemented, pybullet is the api towards the physics/rendering backend, the learning is using stable-baselines3 which is PyTorch based).

For the second one, you can subclass [BaseControl.py](https://github.com/utiasDSL/gym-pybullet-drones/blob/main/gym_pybullet_drones/control/BaseControl.py) as in, for example, [DSLPIDControl.py](https://github.com/utiasDSL/gym-pybullet-drones/blob/main/gym_pybullet_drones/control/DSLPIDControl.py)

**Comment by lakshmikanth-nageswar** [comment]
Thanks for the help!
