### ISSUE TITLE
Different formula for computing RPM

### ISSUE THREAD

**Issue by mfarrelm** [utiasDSL/gym-pybullet-drones#25]
Hi, Jacopo 
Is the matrix A below is used to compute RPM given the torque and force? If it is, why for the calculation of torque x and y, it is divided by 2 not square root of 2. As I know for the X drone model, you divide the total RPM by square root of two

https://github.com/utiasDSL/gym-pybullet-drones/blob/68a96128d506d17891c5f799ae88cfab01486533/gym_pybullet_drones/envs/BaseAviary.py#L167-L171

**Comment by JacopoPan** [comment]
Hi @mfarrelm, thanks for pointing this out, fix'd! `DynAviary`—the one class using RPMs computed from `self.A`—is a bit of a orphaned implementation at this time: if you develop any controller on top of it, please let me know, I'd be happy to include it.
