### ISSUE TITLE
Project Page Stable Baselines3

### ISSUE THREAD

**Issue by araffin** [utiasDSL/gym-pybullet-drones#26]
Hello,

nice project =)

We would be also interested if you could do a pull request on [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) where you add your project to the [documentation](https://stable-baselines3.readthedocs.io/en/master/misc/projects.html) (project section) ;)

**Comment by JacopoPan** [comment]
Thanks @araffin ! I've created a PR in your awesome repo.
