### ISSUE TITLE
Envs difference

### ISSUE THREAD

**Issue by azamkamranian** [utiasDSL/gym-pybullet-drones#47]
Hi. Could someone explain what is difference between env "BaseAviary" with the ("takeoff-aviary-v0", "hover-aviary-v0", and "flythrugate-aviary-v0")?

**Comment by JacopoPan** [comment]
Hi @azamkamranian,

There are essentially 3 layers of implementation:
- `BaseAviary` is a class that implements all is needed to simulate one or more quadcopter (but not RL interfaces)
- Subclasses `BaseSingleAgentAviary` and `BaseMultiagentAviary` extend it with Gym-style action and observation spaces
- Finally, subsubclasses like `HoverAviary` implement the task-specific methods of each Gym (reward, done, info) and other tweaks like normalization and clipping of the observation, obstacles, etc.

**Comment by azamkamranian** [comment]
@JacopoPan thank you for the explanation. yes, I got it.

**Comment by azamkamranian** [comment]
@JacopoPan I know there is so much work but I think a wiki really helps. not only for envs, but a little explaining about the quadcopter physics and ctrl stuff. It really helps to understand functions and ctrl methods for those who are new to drones.

**Comment by JacopoPan** [comment]
I am typically against over complicating documentations but I admit that this repo ballooned a bit w.r.t. to its initial README.
I'm currently working on a new repo with a couple of simple single agent control tasks that should make it easier to approach RL with a controls background and vice versa. I'll revisit this one once the other is released.

**Comment by azamkamranian** [comment]
That is so great.  I want to use new envs for implementing RL algorithms. So, I am looking forward to the new rep too.

**Comment by xiaomaohouhou** [comment]
gym.error.UnregisteredEnv: No registered env with id: takeoff-aviary-v0

The terminal reminds me of this error. Can you help me? Thank you!

**Comment by JacopoPan** [comment]
Hi @xiaomaohouhou 

did you `pip3 install -e .` in the main folder? The registration of the environment is in `gym-pybullet-drones/gym_pybullet_drones/__init__.py`.
