### ISSUE TITLE
Collision detection 

### ISSUE THREAD

**Issue by dd292** [utiasDSL/gym-pybullet-drones#51]
Hey,

I am trying to find out if there is any way to determine collision with obstacles? Do you know if there is any such feature in this implementation or py-bullet in general?

For context, I am planning to add a cost function that can give high costs to collision with objects in the environment.

Thanks

**Comment by JacopoPan** [comment]
Hi @dd292,

yes, PyBullet has APIs that should do what you are looking for under [Collision Detection Queries](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.hrpbzrwzgy1p)

**Comment by sinsauzero** [comment]
> Hi @dd292,
> 
> yes, PyBullet has APIs that should do what you are looking for under [Collision Detection Queries](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.hrpbzrwzgy1p)
> 
> ```
> env = CtrlAviary(..)
> p.getContactPoints(bodyA=env.DRONE_IDS[0],
>                    bodyB=env.DRONE_IDS[1],
>                    linkindexA=-1,
>                    linkindexA=-1,
>                    physicsClientId=env.CLIENT
>                    )
> ```

there's a problem that only the main body of the drone hit the wall get checked and the prop links are ignored so that the prop links all get through the wall without anything happens.  How should I solve this problem?

**Comment by JacopoPan** [comment]
I answered you in #64, @sinsauzero
