### ISSUE TITLE
setStepTime and simulation frequency

### ISSUE THREAD

**Issue by ItsSmarti** [utiasDSL/gym-pybullet-drones#55]
Hey,
thank you so much for this great repository, I really enjoy it!!

From lectures in signal theory I remember the Shannon Theorem, which says that you should sample with twice the frequency of the highest frequency component in the signal.
Basically, we are setting this sampling rate by choosing the simulation frequency in each environment class. So that for each step(..) call the physic engine advances its simulation by 1/frequency. The default rate is set to 240 Hz.

My question is, how did you choose this value? Cause I guess that the signal components of the IMU measurement are higher than 240 Hz / 2 = 120 Hz  (Shannon Theorem).

Thank you so much for your help in advance.
Best regards from Germany - Simon

**Comment by JacopoPan** [comment]
Hi @ItsSmarti,

240Hz is simply the [default stepping frequency of PyBullet](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.5h9ku1yf3u1v) (the underlying physics engine). Yes, the onboard signals/measurement on a real Crazyflie would happen at a higher frequency (but the frequency of the calculations of a controller like the PID one implemented here can be slower).

The choice of `freq` still affects the accuracy of the physical simulations (especially if you have collisions or fast changing dynamics) and you can manually adjust it if your application requires it (I have tried to use 400/500Hz as well when necessary, e.g. in [`compare.py`](https://github.com/utiasDSL/gym-pybullet-drones/blob/master/examples/compare.py) but, of course, it slows down the simulation quite a bit.)
