### ISSUE TITLE
pybullet.error: Cannot load URDF file. numActiveThreads = 0 stopping threads thread  terminated

### ISSUE THREAD

**Issue by vissu1237** [utiasDSL/gym-pybullet-drones#86]
b3Printf: b3Warning[examples/Importers/ImportMeshUtility/b3ImportMeshUtility.cpp,182]:

b3Printf: not found [data/plane/checker_blue.png]

b3Printf: b3Warning[examples/Importers/ImportMeshUtility/b3ImportMeshUtility.cpp,174]:

b3Printf: Unsupported texture image format [./checker_blue.png]

b3Printf: b3Warning[examples/Importers/ImportMeshUtility/b3ImportMeshUtility.cpp,182]:

b3Printf: not found [data/plane/checker_blue.png]

b3Printf: b3Warning[examples/Importers/ImportMeshUtility/b3ImportMeshUtility.cpp,174]:

b3Printf: Unsupported texture image format [./checker_blue.png]

b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frame
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_hand_camera
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frame
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_wrist
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frame
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: head_camera
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,152]:

b3Printf: URDF file 'data/table/table.urdf' not found

Traceback (most recent call last):
  File "C:\Users\PC\Documents\project_codes\_main_.py", line 66, in <module>
    tableId = p.loadURDF(table_path, [1.4, 0, -1], p.getQuaternionFromEuler([0, 0, 1.56]))  # load table
pybullet.error: Cannot load URDF file.
numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 00000000000004AC exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 0000000000000278 exiting
Thread TERMINATED

**Comment by JacopoPan** [comment]
Hi @vissu1237,

this seems related to importing `table_path` (?) in your project `project_codes_main_.py`?
I'm closing the issue for now but feel free to re-open it if you can add some info on how it connects to this project and I'll try to help. 👍
